// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPGVVC8xy46HZH6Z2D5-hKpkklu2mtOQ',
    appId: '1:791332674945:web:2fb65998cba13143c65c80',
    messagingSenderId: '791332674945',
    projectId: 'project-socket-chat-app',
    authDomain: 'project-socket-chat-app.firebaseapp.com',
    storageBucket: 'project-socket-chat-app.appspot.com',
    measurementId: 'G-Q6F9LZBW2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7HZiXG3DV3jAKNUOEsNkkp33rluI--1s',
    appId: '1:791332674945:android:96bc95e3a877291fc65c80',
    messagingSenderId: '791332674945',
    projectId: 'project-socket-chat-app',
    storageBucket: 'project-socket-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLfSh9QVcPIdUoxpAKVqHMXrshtVmTII',
    appId: '1:791332674945:ios:2f5f6b2508c0f51dc65c80',
    messagingSenderId: '791332674945',
    projectId: 'project-socket-chat-app',
    storageBucket: 'project-socket-chat-app.appspot.com',
    iosClientId: '791332674945-hen1aob8sad25flle8sihisbnaophj6d.apps.googleusercontent.com',
    iosBundleId: 'com.dusty.projectSocketChatApp',
  );
}
